apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-app-5
spec:
  selector:
    matchLabels:
      app: mysql-app-5
  template:
    metadata:
      labels:
        app: mysql-app-5
    spec:
      containers:
      - name: mysql-app-5
        image: thiagost32/mysql-app-5:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 3306

---

apiVersion: v1
kind: Service
metadata:
  name: mysql-connection
  labels:
    name: mysql-connection
spec:
  ports:
    - port: 3306 
  selector:
    app: mysql-app5
  clusterIP: None
